<?php
/*
Plugin Name: Codexifyr Website Migrator Importer
Description: Upload one Codexifyr migration ZIP and import its theme, pages, posts, WooCommerce products/variations, categories, menus, SEO, branding and media.
Version: 3.0.0
Author: Codexifyr
*/
if (!defined('ABSPATH')) exit;

define('CXMI_VERSION','3.0.0');
define('CXMI_OPT','cxmi_job');

add_action('admin_menu', function(){
    add_menu_page('Codexifyr Migrator','Codexifyr','manage_options','codexifyr-migrator','cxmi_admin','dashicons-migrate',58);
});

add_action('admin_enqueue_scripts', function($hook){
    if (strpos($hook,'codexifyr-migrator')===false) return;
    wp_enqueue_script('jquery');
});

function cxmi_admin(){
    if (!current_user_can('manage_options')) return;
    $job=get_option(CXMI_OPT,[]);
    ?>
    <div class="wrap">
      <h1>Codexifyr Website Migrator</h1>
      <p>Upload the single migration ZIP generated by the Codexifyr desktop app.</p>
      <?php if (!class_exists('WooCommerce')): ?>
        <div class="notice notice-warning"><p><strong>WooCommerce is not active.</strong> Pages/posts can import, but store products require WooCommerce.</p></div>
      <?php endif; ?>

      <div style="max-width:920px;background:#fff;border:1px solid #dcdcde;padding:22px;margin-top:20px">
        <h2>1. Upload Migration ZIP</h2>
        <form method="post" enctype="multipart/form-data">
          <?php wp_nonce_field('cxmi_upload','cxmi_nonce'); ?>
          <input type="file" name="cxmi_zip" accept=".zip,application/zip" required>
          <?php submit_button('UPLOAD MIGRATION ZIP','primary','cxmi_upload_btn',false); ?>
        </form>
        <?php
        if (!empty($_POST['cxmi_upload_btn'])) cxmi_handle_upload();
        $job=get_option(CXMI_OPT,[]);
        ?>
      </div>

      <div style="max-width:920px;background:#fff;border:1px solid #dcdcde;padding:22px;margin-top:20px">
        <h2>2. Install Website</h2>
        <p id="cxmi-status"><?php echo !empty($job['ready']) ? (($job['stage']??'')==='done' ? 'Previous import complete. You may verify or upload another package.' : 'Migration package ready. Existing progress will resume automatically.') : 'Upload a migration ZIP first.'; ?></p>
        <div style="height:16px;background:#e8e8e8;max-width:760px"><div id="cxmi-bar" style="height:16px;background:#2271b1;width:0%"></div></div>
        <p><button id="cxmi-run" class="button button-primary button-hero" <?php disabled(empty($job['ready'])); ?>><?php echo (!empty($job['ready']) && !empty($job['stage']) && !in_array($job['stage'],['terms','done'],true)) ? 'RESUME IMPORT' : 'INSTALL WEBSITE'; ?></button></p>
        <pre id="cxmi-log" style="max-height:300px;overflow:auto;background:#111;color:#b9ffb9;padding:14px;white-space:pre-wrap"></pre>
      </div>
    </div>
    <script>
    jQuery(function($){
      let running=false;
      $('#cxmi-run').on('click',function(e){
        e.preventDefault();
        if(running)return;
        running=true; $(this).prop('disabled',true);
        $('#cxmi-log').text('');
        function tick(){
          $.post(ajaxurl,{action:'cxmi_step',nonce:'<?php echo esc_js(wp_create_nonce('cxmi_step')); ?>'},function(r){
            if(!r || !r.success){
              let msg=(r&&r.data&&r.data.message)?r.data.message:'Import failed.';
              $('#cxmi-status').text(msg); $('#cxmi-log').append("\nERROR: "+msg); running=false; return;
            }
            let d=r.data||{};
            $('#cxmi-status').text(d.message||'Working...');
            $('#cxmi-bar').css('width',(d.progress||0)+'%');
            if(d.log) $('#cxmi-log').append(d.log+"\n").scrollTop($('#cxmi-log')[0].scrollHeight);
            if(d.done){
              $('#cxmi-status').text('Website import complete.');
              $('#cxmi-bar').css('width','100%');
              running=false; return;
            }
            setTimeout(tick,250);
          }).fail(function(xhr){
            $('#cxmi-status').text('Server request failed. Retry INSTALL WEBSITE to continue.');
            $('#cxmi-log').append("\nServer request failed.");
            running=false;
          });
        }
        tick();
      });
    });
    </script>
    <?php
}

function cxmi_handle_upload(){
    if (!current_user_can('manage_options') || empty($_POST['cxmi_nonce']) || !wp_verify_nonce($_POST['cxmi_nonce'],'cxmi_upload')) return;
    if (empty($_FILES['cxmi_zip']['tmp_name'])) {
        echo '<div class="notice notice-error"><p>No ZIP was uploaded.</p></div>'; return;
    }
    $name=sanitize_file_name($_FILES['cxmi_zip']['name']);
    if (strtolower(pathinfo($name,PATHINFO_EXTENSION))!=='zip'){
        echo '<div class="notice notice-error"><p>Please upload a .zip migration package.</p></div>'; return;
    }

    require_once ABSPATH.'wp-admin/includes/file.php';
    WP_Filesystem();
    $uploads=wp_upload_dir();
    $base=trailingslashit($uploads['basedir']).'codexifyr-migrator';
    wp_mkdir_p($base);
    $dir=$base.'/job-'.time().'-'.wp_generate_password(6,false,false);
    wp_mkdir_p($dir);
    $zip=$dir.'/migration.zip';
    if (!@move_uploaded_file($_FILES['cxmi_zip']['tmp_name'],$zip) && !@copy($_FILES['cxmi_zip']['tmp_name'],$zip)){
        echo '<div class="notice notice-error"><p>Could not save uploaded ZIP.</p></div>'; return;
    }
    $unz=unzip_file($zip,$dir.'/package');
    if (is_wp_error($unz)){
        echo '<div class="notice notice-error"><p>Could not extract migration ZIP: '.esc_html($unz->get_error_message()).'</p></div>'; return;
    }
    $data=cxmi_find_file($dir.'/package','site-data.json');
    if (!$data){
        echo '<div class="notice notice-error"><p>This is not a valid Codexifyr migration ZIP: site-data.json is missing.</p></div>'; return;
    }

    $theme=cxmi_find_file($dir.'/package','codexifyr-source-theme.zip');
    $theme_status='';
    if ($theme){
        $theme_status=cxmi_install_theme($theme);
    }

    $decoded=json_decode(file_get_contents($data),true);
    if (!is_array($decoded)){
        echo '<div class="notice notice-error"><p>site-data.json is invalid.</p></div>'; return;
    }

    update_option(CXMI_OPT,[
        'ready'=>true,'dir'=>$dir,'data'=>$data,'stage'=>'terms','index'=>0,
        'started'=>time(),'theme_status'=>$theme_status,'source_url'=>$decoded['source_url']??''
    ],false);
    echo '<div class="notice notice-success"><p>Migration ZIP loaded. '.esc_html($theme_status).' Click <strong>INSTALL WEBSITE</strong>.</p></div>';
}

function cxmi_find_file($root,$filename){
    if (!is_dir($root)) return '';
    $it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));
    foreach($it as $f) if($f->isFile() && $f->getFilename()===$filename) return $f->getPathname();
    return '';
}

function cxmi_install_theme($zip){
    require_once ABSPATH.'wp-admin/includes/class-wp-upgrader.php';
    require_once ABSPATH.'wp-admin/includes/theme.php';
    $skin=new Automatic_Upgrader_Skin();
    $up=new Theme_Upgrader($skin);
    $r=$up->install($zip,['overwrite_package'=>true]);
    if (is_wp_error($r)) return 'Theme install warning: '.$r->get_error_message();
    $themes=wp_get_themes();
    foreach($themes as $slug=>$theme){
        if (stripos($theme->get('Name'),'Codexifyr Source Store Theme')!==false){
            switch_theme($slug);
            return 'Generated Codexifyr theme installed and activated.';
        }
    }
    return 'Generated theme installed.';
}

function cxmi_data(){
    $j=get_option(CXMI_OPT,[]);
    if(empty($j['data']) || !file_exists($j['data'])) return [[], $j];
    $d=json_decode(file_get_contents($j['data']),true);
    return [is_array($d)?$d:[], $j];
}
function cxmi_save_job($j){ update_option(CXMI_OPT,$j,false); }

add_action('wp_ajax_cxmi_step','cxmi_ajax_step');
function cxmi_ajax_step(){
    check_ajax_referer('cxmi_step','nonce');
    if(!current_user_can('manage_options')) wp_send_json_error(['message'=>'Permission denied.']);
    @set_time_limit(90);
    list($d,$j)=cxmi_data();
    if(empty($j['ready']) || !$d) wp_send_json_error(['message'=>'No valid migration package is loaded.']);

    $stage=$j['stage']??'terms';
    $idx=intval($j['index']??0);
    try{
        if($stage==='terms'){
            cxmi_import_terms($d);
            $j['stage']='content'; $j['index']=0; cxmi_save_job($j);
            wp_send_json_success(['progress'=>5,'message'=>'Categories and tags prepared.','log'=>'✓ Categories and tags prepared']);
        }
        if($stage==='content'){
            $items=array_values(array_filter($d['pages']??[],function($r){return !in_array($r['kind']??'page',['product','category'],true);}));
            $batch=array_slice($items,$idx,5);
            foreach($batch as $r) cxmi_import_content($r);
            $idx+=count($batch);
            if($idx>=count($items)){ $j['stage']='products'; $j['index']=0; }
            else $j['index']=$idx;
            cxmi_save_job($j);
            $p=5+(count($items)?min(20,($idx/count($items))*20):20);
            wp_send_json_success(['progress'=>round($p),'message'=>"Importing pages/blogs {$idx}/".count($items),'log'=>"✓ Pages/blogs processed: {$idx}/".count($items)]);
        }
        if($stage==='products'){
            $items=$d['products']??[];
            $batch=array_slice($items,$idx,2);
            foreach($batch as $p) cxmi_import_product($p);
            $idx+=count($batch);
            if($idx>=count($items)){ $j['stage']='finish'; $j['index']=0; }
            else $j['index']=$idx;
            cxmi_save_job($j);
            $pc=25+(count($items)?min(65,($idx/count($items))*65):65);
            wp_send_json_success(['progress'=>round($pc),'message'=>"Importing products {$idx}/".count($items),'log'=>"✓ Products processed: {$idx}/".count($items)]);
        }
        if($stage==='finish'){
            cxmi_import_menus_branding($d);
            cxmi_set_front_page($d);
            $j['stage']='verify'; $j['index']=0; cxmi_save_job($j);
            wp_send_json_success(['progress'=>96,'message'=>'Website content imported. Running verification…','log'=>'✓ Menus, logo, favicon and homepage settings finished']);
        }
        if($stage==='verify'){
            $verify=cxmi_verify_import($d);
            $j['stage']='done'; $j['index']=0; $j['completed']=time(); $j['verification']=$verify; cxmi_save_job($j);
            $msg='Website import complete. Products '.$verify['imported_products'].'/'.$verify['expected_products'].'; Variations '.$verify['imported_variants'].'/'.$verify['expected_variants'].'; Content '.$verify['imported_content'].'/'.$verify['expected_content'].'.';
            wp_send_json_success(['progress'=>100,'done'=>true,'message'=>$msg,'log'=>'✓ Verification: '.$msg]);
        }
        if($stage==='done'){
            $v=$j['verification']??[];
            $log='✓ Import already complete';
            if($v)$log.=' · Products '.$v['imported_products'].'/'.$v['expected_products'].' · Variations '.$v['imported_variants'].'/'.$v['expected_variants'];
            wp_send_json_success(['progress'=>100,'done'=>true,'message'=>'Website import already complete.','log'=>$log]);
        }
    }catch(Throwable $e){
        wp_send_json_error(['message'=>$e->getMessage()]);
    }
    wp_send_json_error(['message'=>'Unknown import stage.']);
}

function cxmi_media($url,$post=0){
    $url=trim((string)$url); if(!$url) return 0;
    $q=get_posts(['post_type'=>'attachment','post_status'=>'inherit','meta_key'=>'_cx_source_url','meta_value'=>$url,'posts_per_page'=>1,'fields'=>'ids']);
    if($q) return intval($q[0]);
    require_once ABSPATH.'wp-admin/includes/file.php';
    require_once ABSPATH.'wp-admin/includes/media.php';
    require_once ABSPATH.'wp-admin/includes/image.php';
    $tmp=download_url($url,45); if(is_wp_error($tmp)) return 0;
    $path=parse_url($url,PHP_URL_PATH); $name=$path?basename($path):'codexifyr-image.jpg';
    if(!$name || strpos($name,'.')===false) $name='codexifyr-image.jpg';
    $id=media_handle_sideload(['name'=>sanitize_file_name($name),'tmp_name'=>$tmp],$post);
    if(is_wp_error($id)){ @unlink($tmp); return 0; }
    update_post_meta($id,'_cx_source_url',$url);
    return intval($id);
}
function cxmi_find_post($url,$type='any'){
    if(!$url)return 0;
    $q=get_posts(['post_type'=>$type,'post_status'=>'any','meta_key'=>'_cx_source_url','meta_value'=>$url,'posts_per_page'=>1,'fields'=>'ids']);
    return $q?intval($q[0]):0;
}
function cxmi_term($name,$tax,$parent=0){
    $name=trim((string)$name); if(!$name)return 0;
    $e=term_exists($name,$tax,$parent);
    if($e) return is_array($e)?intval($e['term_id']):intval($e);
    $r=wp_insert_term($name,$tax,['parent'=>$parent]);
    return is_wp_error($r)?0:intval($r['term_id']);
}
function cxmi_seo($id,$r){
    $title=$r['meta_title']??''; $desc=$r['meta_description']??'';
    if($title){
        update_post_meta($id,'_yoast_wpseo_title',$title);
        update_post_meta($id,'rank_math_title',$title);
        update_post_meta($id,'_aioseo_title',$title);
    }
    if($desc){
        update_post_meta($id,'_yoast_wpseo_metadesc',$desc);
        update_post_meta($id,'rank_math_description',$desc);
        update_post_meta($id,'_aioseo_description',$desc);
    }
    if(!empty($r['url'])) update_post_meta($id,'_cx_source_url',$r['url']);
}
function cxmi_import_terms($d){
    foreach(($d['blog_categories']??[]) as $c) cxmi_term($c['name']??'','category');
    foreach(($d['tags']??[]) as $t) cxmi_term($t['name']??'','post_tag');

    // Product categories: parents first, then a few passes to resolve hierarchy.
    $cats=$d['categories']??[];
    foreach($cats as $c) if(empty($c['parent'])) cxmi_term($c['name']??'','product_cat',0);
    for($pass=0;$pass<4;$pass++){
        foreach($cats as $c){
            $name=$c['name']??''; $parent_name=$c['parent']??'';
            $parent=0;
            if($parent_name){$e=term_exists($parent_name,'product_cat'); if($e)$parent=is_array($e)?intval($e['term_id']):intval($e);}
            $id=cxmi_term($name,'product_cat',$parent);
            if($id){
                if(!empty($c['description_html'])) wp_update_term($id,'product_cat',['description'=>wp_kses_post($c['description_html'])]);
                if(!empty($c['meta_title'])) update_term_meta($id,'rank_math_title',$c['meta_title']);
                if(!empty($c['meta_description'])) update_term_meta($id,'rank_math_description',$c['meta_description']);
            }
        }
    }
}
function cxmi_import_content($r){
    $kind=$r['kind']??'page'; $type=$kind==='blog'?'post':'page';
    $old=cxmi_find_post($r['url']??'',$type);
    $arr=[
        'ID'=>$old?:0,'post_type'=>$type,'post_status'=>'publish',
        'post_title'=>$r['title']??'Untitled','post_name'=>$r['slug']??'',
        'post_content'=>$r['body_html']??'','post_excerpt'=>$r['excerpt']??''
    ];
    if($type==='post' && !empty($r['published_date'])){
        $ts=strtotime($r['published_date']); if($ts){$arr['post_date']=date('Y-m-d H:i:s',$ts);$arr['post_date_gmt']=gmdate('Y-m-d H:i:s',$ts);}
    }
    $id=wp_insert_post($arr,true); if(is_wp_error($id)) return;
    cxmi_seo($id,$r);
    if(!empty($r['featured_image'])){$aid=cxmi_media($r['featured_image'],$id);if($aid)set_post_thumbnail($id,$aid);}
    if($type==='post'){
        $cats=[]; foreach(($r['categories']??[]) as $n){$tid=cxmi_term($n,'category');if($tid)$cats[]=$tid;}
        if($cats) wp_set_post_categories($id,$cats,false);
        if(!empty($r['tags'])) wp_set_post_tags($id,$r['tags'],false);
    }
}
function cxmi_import_product($p){
    if(!class_exists('WooCommerce')) return;
    $old=cxmi_find_post($p['url']??'','product');
    $pid=wp_insert_post([
        'ID'=>$old?:0,'post_type'=>'product','post_status'=>'publish',
        'post_title'=>$p['title']??'Untitled Product','post_name'=>$p['slug']??'',
        'post_content'=>$p['description_html']??'','post_excerpt'=>$p['short_description_html']??''
    ],true);
    if(is_wp_error($pid)) return;
    cxmi_seo($pid,$p);
    if(!empty($p['sku'])) update_post_meta($pid,'_sku',$p['sku']);

    $cats=[];
    foreach(($p['categories']??[]) as $c){$tid=cxmi_term($c,'product_cat');if($tid)$cats[]=$tid;}
    if($cats) wp_set_object_terms($pid,array_values(array_unique($cats)),'product_cat',false);
    if(!empty($p['tags'])) wp_set_object_terms($pid,$p['tags'],'product_tag',false);

    $gallery=[];
    foreach(($p['images']??[]) as $ix=>$u){
        $aid=cxmi_media($u,$pid); if(!$aid)continue;
        if($ix===0)set_post_thumbnail($pid,$aid); else $gallery[]=$aid;
    }
    if($gallery)update_post_meta($pid,'_product_image_gallery',implode(',',$gallery));

    $vars=$p['variants']??[];
    $real=false; foreach($vars as $v) if(!empty(array_filter($v['options']??[]))){$real=true;break;}

    if(!$real){
        wp_set_object_terms($pid,'simple','product_type');
        $v=$vars[0]??[];
        $price=(string)($v['price']??'');
        $compare=(string)($v['compare_at_price']??'');
        $regular=$compare!==''?$compare:($v['regular_price']??$price);
        $sale=($compare!=='' && $price!=='')?$price:'';
        update_post_meta($pid,'_regular_price',$regular);
        update_post_meta($pid,'_sale_price',$sale);
        update_post_meta($pid,'_price',$sale!==''?$sale:$regular);
        $available=array_key_exists('available',$v)?!empty($v['available']):true;
        update_post_meta($pid,'_stock_status',$available?'instock':'outofstock');
        if(($v['inventory_qty']??'')!==''){
            update_post_meta($pid,'_manage_stock','yes'); update_post_meta($pid,'_stock',$v['inventory_qty']);
        }
        return;
    }

    wp_set_object_terms($pid,'variable','product_type');
    $values=[];
    foreach($vars as $v){
        foreach(($v['options']??[]) as $i=>$val){
            if($val==='')continue;
            $n=$v['option_names'][$i]??('Option '.($i+1));
            if(!isset($values[$n]))$values[$n]=[];
            $values[$n][]=$val;
        }
    }
    $attrs=[];$pos=0;
    foreach($values as $n=>$vals){
        $attrs[sanitize_title($n)]=[
            'name'=>$n,'value'=>implode(' | ',array_values(array_unique($vals))),
            'position'=>$pos++,'is_visible'=>1,'is_variation'=>1,'is_taxonomy'=>0
        ];
    }
    update_post_meta($pid,'_product_attributes',$attrs);

    // Reimport safely: remove old generated variations for this source product.
    $oldvars=get_children(['post_parent'=>$pid,'post_type'=>'product_variation','post_status'=>'any','numberposts'=>-1,'fields'=>'ids']);
    foreach($oldvars as $ov) wp_delete_post($ov,true);

    foreach($vars as $v){
        $vid=wp_insert_post([
            'post_type'=>'product_variation','post_status'=>'publish','post_parent'=>$pid,
            'post_title'=>($p['title']??'Product').' - '.($v['title']??'Variation')
        ],true);
        if(is_wp_error($vid))continue;
        foreach(($v['options']??[]) as $i=>$val){
            if($val==='')continue;
            $n=$v['option_names'][$i]??('Option '.($i+1));
            update_post_meta($vid,'attribute_'.sanitize_title($n),sanitize_title($val));
        }
        $price=(string)($v['price']??'');
        $compare=(string)($v['compare_at_price']??'');
        $regular=$compare!==''?$compare:($v['regular_price']??$price);
        $sale=($compare!=='' && $price!=='')?$price:'';
        update_post_meta($vid,'_regular_price',$regular);
        update_post_meta($vid,'_sale_price',$sale);
        update_post_meta($vid,'_price',$sale!==''?$sale:$regular);
        if(!empty($v['sku']))update_post_meta($vid,'_sku',$v['sku']);
        $available=array_key_exists('available',$v)?!empty($v['available']):true;
        update_post_meta($vid,'_stock_status',$available?'instock':'outofstock');
        if(($v['inventory_qty']??'')!==''){
            update_post_meta($vid,'_manage_stock','yes');update_post_meta($vid,'_stock',$v['inventory_qty']);
        }
        if(!empty($v['image'])){$aid=cxmi_media($v['image'],$vid);if($aid)set_post_thumbnail($vid,$aid);}
        if(!empty($v['variation_id']))update_post_meta($vid,'_cx_source_variant_id',(string)$v['variation_id']); elseif(!empty($v['id']))update_post_meta($vid,'_cx_source_variant_id',(string)$v['id']);
    }
    if(class_exists('WC_Product_Variable')) WC_Product_Variable::sync($pid);
    wc_delete_product_transients($pid);
}
function cxmi_menu_items($mid,$items,$parent=0){
    foreach($items as $i){
        $url=$i['url']??'#';$title=$i['title']??'Menu';$pid=cxmi_find_post($url);
        $args=['menu-item-title'=>$title,'menu-item-url'=>$url,'menu-item-status'=>'publish','menu-item-parent-id'=>$parent];
        if($pid){$args['menu-item-object-id']=$pid;$args['menu-item-object']=get_post_type($pid);$args['menu-item-type']='post_type';}
        else{$args['menu-item-object']='custom';$args['menu-item-type']='custom';}
        $id=wp_update_nav_menu_item($mid,0,$args);
        if(!is_wp_error($id)&&!empty($i['children']))cxmi_menu_items($mid,$i['children'],$id);
    }
}
function cxmi_import_menus_branding($d){
    $locations=get_theme_mod('nav_menu_locations',[]);
    foreach(($d['menus']??[]) as $ix=>$m){
        $name=$m['name']??('Codexifyr Menu '.($ix+1));
        $obj=wp_get_nav_menu_object($name);
        $mid=$obj?$obj->term_id:wp_create_nav_menu($name);
        if(is_wp_error($mid))continue;
        // Clear existing items so retries don't duplicate menu entries.
        $items=wp_get_nav_menu_items($mid); if($items)foreach($items as $it)wp_delete_post($it->ID,true);
        cxmi_menu_items($mid,$m['items']??[]);
        $lname=strtolower($name);
        if(!isset($locations['primary']) || strpos($lname,'main')!==false || strpos($lname,'header')!==false) $locations['primary']=$mid;
        if(strpos($lname,'footer')!==false) $locations['footer']=$mid;
    }
    set_theme_mod('nav_menu_locations',$locations);
    if(!empty($d['branding']['logo'])){$aid=cxmi_media($d['branding']['logo']);if($aid)set_theme_mod('custom_logo',$aid);}
    if(!empty($d['branding']['favicon'])){$aid=cxmi_media($d['branding']['favicon']);if($aid)update_option('site_icon',$aid);}
}
function cxmi_set_front_page($d){
    $root=rtrim($d['source_url']??'','/');
    if(!$root)return;
    foreach(($d['pages']??[]) as $r){
        if(($r['kind']??'page')!=='page')continue;
        if(rtrim($r['url']??'','/')===$root){
            $id=cxmi_find_post($r['url']??'','page');
            if($id){update_option('show_on_front','page');update_option('page_on_front',$id);}
            break;
        }
    }
}


function cxmi_verify_import($d){
    $expected_products=count($d['products']??[]);
    $expected_variants=0;
    foreach(($d['products']??[]) as $p){
        $vars=$p['variants']??[];$real=false;
        foreach($vars as $v) if(!empty(array_filter($v['options']??[]))){$real=true;break;}
        if($real)$expected_variants+=count($vars);
    }
    $content=array_values(array_filter($d['pages']??[],function($r){return !in_array($r['kind']??'page',['product','category'],true);}));
    $expected_content=count($content);
    $imported_products=0;$imported_variants=0;$imported_content=0;
    foreach(($d['products']??[]) as $p){
        $pid=cxmi_find_post($p['url']??'','product');
        if($pid){
            $imported_products++;
            $imported_variants+=count(get_children(['post_parent'=>$pid,'post_type'=>'product_variation','post_status'=>'any','numberposts'=>-1,'fields'=>'ids']));
        }
    }
    foreach($content as $r){
        $type=($r['kind']??'page')==='blog'?'post':'page';
        if(cxmi_find_post($r['url']??'',$type))$imported_content++;
    }
    return compact('expected_products','imported_products','expected_variants','imported_variants','expected_content','imported_content');
}
